name: Generate terraform docs
on:
  - pull_request
jobs:
  docs:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the README.md and push changes back to PR branch (module)
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: module
        output-file: README.md
        output-method: inject
        git-push: "true"
